import { Product, Category, Banner, Order } from "../types";

export const MOCK_BANNERS: Banner[] = [
  {
    id: "b1",
    title: "The Signature Audio Drop",
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&auto=format&fit=crop",
    linkUrl: "/products",
    position: "HERO_CAROUSEL",
    isActive: true,
    order: 1,
  },
  {
    id: "b2",
    title: "Precision Mechanical Keyboards",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=1200&auto=format&fit=crop",
    linkUrl: "/products?categorySlug=electronics",
    position: "HERO_CAROUSEL",
    isActive: true,
    order: 2,
  },
  {
    id: "b3",
    title: "Summer Minimalist Apparel",
    imageUrl: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=1200&auto=format&fit=crop",
    linkUrl: "/products?categorySlug=fashion-apparel",
    position: "HERO_CAROUSEL",
    isActive: true,
    order: 3,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "c1",
    slug: "electronics",
    name: "Electronics",
    description: "Audio, smart gear & verified tech",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop",
    productCount: 48,
  },
  {
    id: "c2",
    slug: "mobiles-tablets",
    name: "Mobiles",
    description: "Flagship smartphones and certified pre-owned",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02547?w=400&auto=format&fit=crop",
    productCount: 32,
  },
  {
    id: "c3",
    slug: "computers-laptops",
    name: "Computers",
    description: "Monitors, mechanical keyboards & laptops",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&auto=format&fit=crop",
    productCount: 26,
  },
  {
    id: "c4",
    slug: "fashion-apparel",
    name: "Fashion",
    description: "Minimalist streetwear and organic cotton basics",
    imageUrl: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&auto=format&fit=crop",
    productCount: 64,
  },
  {
    id: "c5",
    slug: "home-kitchen",
    name: "Home Living",
    description: "Artisan ceramics, decor and coffee gear",
    imageUrl: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=400&auto=format&fit=crop",
    productCount: 29,
  },
  {
    id: "c6",
    slug: "gaming",
    name: "Gaming",
    description: "Controllers, mice & gaming stations",
    imageUrl: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=400&auto=format&fit=crop",
    productCount: 18,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "sonic-pro-wireless-headphones",
    title: "SonicPro Active Noise Cancelling Wireless Headphones",
    description: "Engineered for immersive acoustic fidelity. Featuring custom 40mm titanium drivers, 45-hour battery life, and hybrid ANC.",
    brand: "Aura Acoustics",
    condition: "New",
    categoryName: "Electronics",
    categorySlug: "electronics",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop",
    ],
    priceCents: 499900,
    compareAtCents: 799900,
    discountPercent: 38,
    sellerName: "Aura Official India",
    sellerFulfillment: "cartigo",
    availableStock: 18,
    variants: [
      { id: "v1-1", sku: "AUR-BLK-01", priceCents: 499900, compareAtCents: 799900, availableStock: 12, options: { color: "Matte Black" } },
      { id: "v1-2", sku: "AUR-SLV-02", priceCents: 529900, compareAtCents: 849900, availableStock: 6, options: { color: "Moon Silver" } },
    ],
    attributes: [
      { key: "Battery Life", value: "45 Hours (ANC On)" },
      { key: "Connectivity", value: "Bluetooth 5.3 + 3.5mm Aux" },
      { key: "Weight", value: "248g" },
      { key: "Warranty", value: "1 Year Manufacturer Replacement" },
    ],
  },
  {
    id: "p2",
    slug: "vanguard-mechanical-keyboard",
    title: "Vanguard Tenkeyless RGB Wireless Mechanical Keyboard",
    description: "CNC aluminum chassis with hot-swappable lubricated Gateron Pro Yellow switches and seamless tri-mode 2.4GHz connectivity.",
    brand: "KeebCraft",
    condition: "New",
    categoryName: "Computers",
    categorySlug: "computers-laptops",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&auto=format&fit=crop",
    ],
    priceCents: 649900,
    compareAtCents: 899900,
    discountPercent: 28,
    sellerName: "KeebCraft Studio",
    sellerFulfillment: "cartigo",
    availableStock: 14,
    variants: [
      { id: "v2-1", sku: "KB-YLW-01", priceCents: 649900, compareAtCents: 899900, availableStock: 10, options: { switch: "Gateron Yellow Linear" } },
      { id: "v2-2", sku: "KB-BRN-02", priceCents: 649900, compareAtCents: 899900, availableStock: 4, options: { switch: "Gateron Brown Tactile" } },
    ],
    attributes: [
      { key: "Layout", value: "80% Tenkeyless (87 Keys)" },
      { key: "Switches", value: "Hot-Swappable 5-Pin PCB" },
      { key: "Chassis", value: "Anodized Solid Aluminum" },
    ],
  },
  {
    id: "p3",
    slug: "nordic-minimalist-daypack",
    title: "Nordic Weatherproof Laptop Daypack 22L",
    description: "Minimalist commuter backpack crafted from recycled 900D ballistic nylon with dedicated 16-inch padded laptop compartment.",
    brand: "Kovert Goods",
    condition: "New",
    categoryName: "Fashion",
    categorySlug: "fashion-apparel",
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop",
    ],
    priceCents: 349900,
    compareAtCents: 499900,
    discountPercent: 30,
    sellerName: "Urban Carry Co.",
    sellerFulfillment: "reseller",
    availableStock: 25,
    variants: [
      { id: "v3-1", sku: "BP-BLK-01", priceCents: 349900, compareAtCents: 499900, availableStock: 15, options: { color: "Charcoal" } },
      { id: "v3-2", sku: "BP-OLV-02", priceCents: 349900, compareAtCents: 499900, availableStock: 10, options: { color: "Olive Green" } },
    ],
    attributes: [
      { key: "Capacity", value: "22 Liters" },
      { key: "Material", value: "Water-resistant 900D Cordura" },
      { key: "Laptop Pocket", value: "Fits up to 16\" MacBook Pro" },
    ],
  },
  {
    id: "p4",
    slug: "lumina-smart-desk-lamp",
    title: "Lumina Studio Architect LED Desk Light with Wireless Charger",
    description: "High CRI 98 glare-free diffused illumination with touch sliding dimmer and 15W Qi fast charging base.",
    brand: "Lumina Labs",
    condition: "New",
    categoryName: "Home Living",
    categorySlug: "home-kitchen",
    imageUrl: "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?w=800&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?w=800&auto=format&fit=crop",
    ],
    priceCents: 279900,
    compareAtCents: 399900,
    discountPercent: 30,
    sellerName: "Lumina Direct",
    sellerFulfillment: "cartigo",
    availableStock: 22,
    variants: [
      { id: "v4-1", sku: "LUM-WHT-01", priceCents: 279900, compareAtCents: 399900, availableStock: 22, options: { color: "Matte White" } },
    ],
    attributes: [
      { key: "Color Accuracy", value: "CRI 98 True Tone" },
      { key: "Power Output", value: "15W Qi Wireless Fast Charging" },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-1",
    orderNumber: "CTG-2026-84912",
    status: "SHIPPED",
    subtotalCents: 499900,
    shippingCents: 0,
    taxCents: 89982,
    totalCents: 589882,
    currency: "INR",
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    paymentMethod: "CARD",
    items: [
      {
        id: "item-1",
        variantId: "v1-1",
        titleSnapshot: "SonicPro Active Noise Cancelling Wireless Headphones (Matte Black)",
        skuSnapshot: "AUR-BLK-01",
        unitPriceCentsSnap: 499900,
        quantity: 1,
      },
    ],
  },
  {
    id: "ord-2",
    orderNumber: "CTG-2026-61203",
    status: "DELIVERED",
    subtotalCents: 349900,
    shippingCents: 0,
    taxCents: 62982,
    totalCents: 412882,
    currency: "INR",
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    paymentMethod: "COD",
    items: [
      {
        id: "item-2",
        variantId: "v3-1",
        titleSnapshot: "Nordic Weatherproof Laptop Daypack 22L (Charcoal)",
        skuSnapshot: "BP-BLK-01",
        unitPriceCentsSnap: 349900,
        quantity: 1,
      },
    ],
  },
];
